mode: debug

http:
  host: 0.0.0.0
  port: 8888

ssh:
  host: 0.0.0.0
  port: 2222
  privateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACBg490b4zqumtizCyM4RWtzJnPEsPIInBFugk8+UCb8XgAAAKCc1yKrnNci
    qwAAAAtzc2gtZWQyNTUxOQAAACBg490b4zqumtizCyM4RWtzJnPEsPIInBFugk8+UCb8Xg
    AAAECvd1Yj+bQxyxJtU3PirLK68CD3MWqBv0/shlFKS6wmbWDj3RvjOq6a2LMLIzhFa3Mm
    c8Sw8gicEW6CTz5QJvxeAAAAGnJvb3RAbG9jYWxob3N0LmxvY2FsZG9tYWluAQID
    -----END OPENSSH PRIVATE KEY-----


guacd:
  host: oneterm-guacd
  port: 4822

mysql:
  host: mysql
  port: 3306
  user: root
  password: "123456"

redis:
  host: redis
  port: 6379
  password: ""

log:
  level: debug
  format: json
  maxSize: 1
  consoleEnable: true

auth:
  acl:
    appId: 5867e079dfd1437e9ae07576ab24b391
    secretKey: 2qlTA4z@#KyigJLYHGrev?0WD6hjX*8E
    url: http://acl-api:5000/api/v1
  aes:
    key: thisis32bitlongpassphraseimusing
    iv: 0123456789abcdef

secretKey: xW2FAUfgffjmerTEBXADmURDOQ43ojLN
